import type { Metadata } from "next";
export const metadata: Metadata = { title: "Documentation" };
const code = `{
  "protocol": "first/1",
  "id": "01997ef0-…",
  "type": "agent",
  "part": 1,
  "total": 2,
  "data": "{\\"name\\":\\"atlas\\"…"
}`;
export default function DocsPage(){return <main><div className="shell"><header className="page-head"><span className="eyebrow"><i/> Protocol reference</span><h1>Docs</h1><p>Everything needed to create, verify, index, and extend First artifacts.</p></header><div className="docs-layout"><aside className="docs-nav"><a href="#quickstart">Quickstart</a><br/><a href="#protocol">Inscription protocol</a><br/><a href="#types">Artifact types</a><br/><a href="#tokens">Token launches</a><br/><a href="#agents">Agent manifests</a><br/><a href="#security">Security</a><br/><a href="#deploy">Deployment</a></aside><article className="prose">
  <h2 id="quickstart">Quickstart</h2><p>First is a client-first Solana creation studio. Connect a wallet, stay on devnet while testing, choose a primitive, preview the payload, and approve each transaction in your wallet. The platform never receives a private key and never signs for a user.</p><ol><li>Copy <code>.env.example</code> to <code>.env.local</code>.</li><li>Set a reliable Solana RPC endpoint and a 32+ character session secret.</li><li>Run <code>npm install</code>, then <code>npm run dev</code>.</li><li>Open the Studio and connect a Wallet Standard compatible wallet.</li></ol>
  <h2 id="protocol">Inscription protocol</h2><p>First stores an envelope as UTF‑8 instruction data using the audited SPL Memo program. The signer account is included in the instruction, so indexers can verify authorship. A payload may span multiple transactions; every part shares an immutable UUID.</p><pre className="code">{code}</pre><h3>Reassembly</h3><p>Find memo instructions whose program ID is <code>MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr</code>, parse envelopes with <code>protocol: first/1</code>, group by <code>id</code>, order by <code>part</code>, verify all parts share the expected signer, and concatenate <code>data</code>.</p><p>The studio targets 720 payload bytes per part. This deliberately leaves headroom for the envelope, account keys, blockhash, and signature within Solana&apos;s transaction packet limit.</p>
  <h2 id="types">Artifact types</h2><ul><li><code>text</code> — arbitrary UTF‑8.</li><li><code>json</code> — validated and minified JSON.</li><li><code>image</code> — typically a compact SVG or data URI. Large raster files are intentionally discouraged.</li><li><code>agent</code> — a normalized <code>first/agent/1</code> manifest.</li></ul>
  <h2 id="tokens">Token launches</h2><p>Coin launches use the Token‑2022 program. First creates a mint with Metadata Pointer and Token Metadata extensions, stores the name, symbol, and URI on the mint account, creates the owner&apos;s associated token account, and mints the configured supply. When “fixed supply” is enabled, the studio revokes the mint authority after minting. That action cannot be reversed.</p><p>Launching a mint does not create a market, liquidity pool, or promise of value. Mainnet operators should add jurisdiction-appropriate disclosures and review token configuration with counsel.</p>
  <h2 id="agents">Agent manifests</h2><p>An agent manifest is not executable bytecode. It is a durable, owner-signed discovery record containing a name, semantic version, HTTPS endpoint, description, and declared capabilities. Consumers must treat endpoint content as untrusted and independently authenticate responses.</p><pre className="code">{`{
  "protocol": "first/agent/1",
  "name": "atlas",
  "version": "1.0.0",
  "endpoint": "https://agent.example/.well-known/agent.json",
  "capabilities": ["research", "execute"]
}`}</pre>
  <h2 id="security">Security model</h2><ul><li>Wallet authentication is Sign‑In With Solana style: a short-lived nonce, detached Ed25519 signature verification, and an HTTP-only SameSite session cookie.</li><li>Vanity keypairs are generated only in browser memory. Download once, store securely, and never paste a secret key into the site.</li><li>Every transaction is built client-side and explicitly signed by the connected wallet.</li><li>Production deployments must set <code>SESSION_SECRET</code>, use HTTPS, configure a private RPC, enable monitoring, and keep dependencies patched.</li><li>Review transaction simulations and use devnet before mainnet. Blockchain writes and authority revocations are irreversible.</li></ul>
  <h2 id="deploy">Production deployment</h2><p>The app is a standard Next.js service and can run on Vercel, Cloud Run, or any Node 20+ container. Configure <code>NEXT_PUBLIC_SOLANA_NETWORK=mainnet-beta</code>, a paid <code>NEXT_PUBLIC_SOLANA_RPC_URL</code>, <code>NEXT_PUBLIC_APP_URL</code>, and a strong <code>SESSION_SECRET</code>. Add rate limiting at the edge for authentication routes. Static pages are cacheable; wallet and RPC calls remain client-side.</p><h3>Verification checklist</h3><ul><li><code>npm run typecheck</code></li><li><code>npm test</code></li><li><code>npm run build</code></li><li>Exercise a complete devnet inscription and token launch with a disposable wallet.</li><li>Confirm CSP and observability policy for your deployment provider.</li></ul>
  <h2>Protocol status</h2><p><code>first/1</code> is intentionally small and open. The repository is the canonical specification. Backward-incompatible revisions must use a new protocol string.</p>
  </article></div></div></main>}
