"use client";
import { useState } from "react";
import { Search } from "lucide-react";
import { DEFAULT_RPC, MEMO_PROGRAM_ADDRESS, explorerUrl } from "@/lib/constants";
import { decodeFirstEnvelope, validateTransactionSignature } from "@/lib/explorer";

type Decoded={signature:string;slot:number;payload:string}|null;
export function ExplorerSearch(){const[sig,setSig]=useState("");const[result,setResult]=useState<Decoded>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 const run=async()=>{try{setBusy(true);setError("");setResult(null);const signature=validateTransactionSignature(sig);const response=await fetch(process.env.NEXT_PUBLIC_SOLANA_RPC_URL||DEFAULT_RPC,{method:"POST",headers:{"content-type":"application/json"},signal:AbortSignal.timeout(15_000),body:JSON.stringify({jsonrpc:"2.0",id:"first",method:"getTransaction",params:[signature,{encoding:"jsonParsed",commitment:"confirmed",maxSupportedTransactionVersion:1}]})});if(!response.ok)throw new Error(`RPC returned HTTP ${response.status}.`);const rpc=await response.json();if(rpc.error)throw new Error(rpc.error.message||"RPC request failed");const tx=rpc.result;if(!tx)throw new Error("Transaction not found on the selected network.");const instructions=tx.transaction?.message?.instructions;if(!Array.isArray(instructions))throw new Error("RPC returned an invalid transaction response.");let envelope;for(const instruction of instructions){if(instruction.programId!==MEMO_PROGRAM_ADDRESS)continue;const raw=typeof instruction.parsed==="string"?instruction.parsed:instruction.data?new TextDecoder().decode((await import("bs58")).default.decode(instruction.data)):null;if(!raw)continue;try{envelope=decodeFirstEnvelope(raw);break}catch{continue}}if(!envelope)throw new Error("No valid first/1 inscription was found in this transaction.");setResult({signature,slot:Number(tx.slot),payload:JSON.stringify(envelope,null,2)});}catch(e){setError(e instanceof Error?e.message:"Lookup failed")}finally{setBusy(false)}};
 return <><div className="panel" style={{marginBottom:40}}><div className="field"><label>Transaction signature</label><div style={{display:"flex",gap:10}}><input value={sig} onChange={e=>setSig(e.target.value)} placeholder="Paste a Solana transaction signature"/><button className="button" disabled={!sig||busy} onClick={run}><Search size={15}/>{busy?"Reading…":"Decode"}</button></div></div>{error&&<div className="status error">{error}</div>}{result&&<div className="status success"><b>Slot {result.slot.toLocaleString()}</b><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{result.payload}</pre><a href={explorerUrl(result.signature)} target="_blank" rel="noreferrer"><u>Open raw transaction</u></a></div>}</div></>}
